#!/usr/bin/env python
# simple script for easily displaying IP address in terminal
import socket

try:
	socket.gethostbyname(socket.gethostname())
except socket.error as msg:
    print "Not connected to the interwebs"
    sys.exit(-1)

print socket.gethostbyname(socket.gethostname())
